name: APT Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        run: |
          docker run --pull always -t --user root "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" sh -c '
            apt-get update
            if apt-get -s upgrade | tee -a /dev/stderr | grep -q -e '"'"'^Inst '"'"' ; then
              exit 1
            fi
          '
